### ISSUE TITLE
support autodaemonization

### ISSUE THREAD

**Issue by ethanpailes** [shell-pool/shpool#56]
Most similar tools don't use systemd to manage the daemon, they just autodaemonize. We should support such a mode to make life easier for people who don't use systemd.

**Comment by ethanpailes** [comment]
I just posted https://github.com/shell-pool/shpool/pull/98 which fixes this issue, but it requires an opt-in flag. Part of me thinks that making it the default behavior might be better since we should first try to use systemd and the fallback on autodamonization, so systemd users should not be impacted if we make this the default.

Does anyone have thoughts?

**Comment by ethanpailes** [comment]
cc @someplaceguy @qaqland @dropwhile @joshbainbridge @fedemp @merrickluo @dbohdan about the default behavior question since you all have expressed interest in the feature

**Comment by someplaceguy** [comment]
> I just posted #98 which fixes this issue, but it requires an opt-in flag. Part of me thinks that making it the default behavior might be better since we should first try to use systemd and the fallback on autodamonization, so systemd users should not be impacted if we make this the default.
> 
> Does anyone have thoughts?

I wasn't planning to, but I think I'm going to stick with the systemd daemon after all, for reliability reasons (that is, once #46 and hopefully #71 are solved, so that shpool becomes usable for my purposes).

That said, if I had to use autodaemonization, personally I think I would prefer having an opt-in flag, to make sure the behavior is more predictable.

There are two concerns I have with the current implementation of autodaemonization:

1.  If multiple `shpool` processes are started at exactly the same time, in parallel, with autodaemonization turned on, am I correct to assume that the user might end up with multiple background daemons running, all of which eventually becoming inaccessible except for one?
I'm thinking this might happen due to a race condition where multiple `shpool` processes starting at the same time try to connect to the control socket, fail, which would cause all of them to decide to start a background daemon. These background daemons then might take slightly different times to start and take control of the socket, which could cause some sessions to become inaccessible when the other daemons take control of the socket, I assume?

2. Personally, I also don't like that there is a timeout to try to connect to the control socket. I have a build machine that runs with an extremely high user load (so as to make sure that all cores are always being used) and basically, any sort of command that has a (reasonable) timeout becomes unreliable, since the timeouts will trigger quite often just as a result of the machine being extremely busy.

**Comment by ethanpailes** [comment]
(1) is a good concern. I think is is sovled by the fact that the multiple daemon processes will race to see who gets to crate the control socket and the first one will be the winner, with the others all just bailing, but I should check.

In terms of (2), I do want there to be some timeout since I don't think hanging forever is very friendly, but maybe we can bump it up from 5 to 10 seconds?

**Comment by someplaceguy** [comment]
> In terms of (2), I do want there to be some timeout since I don't think hanging forever is very friendly, but maybe we can bump it up from 5 to 10 seconds?

If you're going to have a timeout, then don't increase it to 10 seconds (or any other reasonable number) on my account, since it won't make any difference in my environment -- it will only cause the timeouts to get hit a bit less frequently.

For my purposes, I'd rather prefer a reliable solution instead; namely, an option to disable the timeouts altogether. But again, there's no need to create this option just for my use case, because when I am able to use `shpool`, I'm planning to use the systemd daemon anyway (and I assume that when the systemd daemon is being used, there is no such timeout, right?).

BTW: it seems that the "Without systemd" instructions contain a command to enable the systemd daemon, so I assume that's a copy/paster error? See: https://github.com/shell-pool/shpool/commit/989baf0673039e49aa7d36d42818c53ec98592e7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R35

**Comment by dbohdan** [comment]
I don't feel strongly about requiring a flag for autodaemonization. I do have two related points.

First, something I think is fairly important that if autodaemonization without a flag is implemented, whether shpool starts a daemon automatically should depend on the command the user gives it. Specifically, shpool should autodaemonize when the command is `attach` and not when it is another command or there is no command. This would be similar to tmux: tmux doesn't start a daemon, for example, on `tmux ls` or `tmux split-window`; it starts one when you create a new session. (tmux also doesn't start a daemon on `tmux attach`, but that's because it has a separate `new` command, and shpool doesn't. While tmux starts a daemon without arguments, that's because `tmux` without arguments acts like `tmux new`.) Again, this only applies if no flag is required.

Second, `-D` is IMO a bad choice of short flag for `--daemonize`. The common meaning of `-D`, for example, in [tmux](https://man.openbsd.org/tmux.1) or [mini_httpd](https://manpages.debian.org/testing/mini-httpd/mini_httpd.8.en.html), is to **not** start a daemon.

**Comment by ethanpailes** [comment]
@someplaceguy 

> I assume that when the systemd daemon is being used, there is no such timeout, right?

Yeah that's right.

> I'd rather prefer a reliable solution instead; namely, an option to disable the timeouts altogether. But again, there's no need to create this option just for my use case

That's a good point a config option is probably the way to go. Just because you probably won't need it doesn't mean someone won't want it.

@dbohdan 

I'm not sure I agree about only daemonizing on attach. That may be what tmux does, but it's not what every tool does. In particular, I'm thinking of adb which autodamonises for `adb devices` (basically a list command). I think the consistency of having all your client commands work the same wether you have a daemon running yet or not is good. It seems weird to me that `shpool list` would behave differently depending on if you ran `shpool attach whatever` first.

> Second, -D is IMO a bad choice of short flag for --daemonize. The common meaning of -D, for example, in [tmux](https://man.openbsd.org/tmux.1) or [mini_httpd](https://manpages.debian.org/testing/mini-httpd/mini_httpd.8.en.html), is to not start a daemon.

hmm, interesting, I was just using avahi where -D means to daemonize, but obviously tmux is much more relavant here. I can switch it it `-d`

**Comment by someplaceguy** [comment]
> That said, if I had to use autodaemonization, personally I think I would prefer having an opt-in flag, to make sure the behavior is more predictable.

Correction: if I had to use autodaemonization, I would prefer either an opt-in or an opt-out flag (but it doesn't matter which). That is, as long I could choose the behavior, it would be fine by me.

**Comment by joshbainbridge** [comment]
I might not be the most experienced of users. But my two cents, I'd say less friction the better for new users. While also, if possible, not compromising on best practice (systemd).

With that in mind, if systemd (or launchd on macOS, etc) is active then I'd hope it would use that service. If it has been setup, then great, that's considered best practice.

But if no daemon is active, then autodaemonize by default, as many users will expect that behaviour (tmux, screen, zellij, tab). And opt out of autodaemonize with a flag.

But honestly supper happy with any option. Thank you for all the great work!

**Comment by dbohdan** [comment]
@ethanpailes

From my perspective, `foo list` is like a GET HTTP request and shouldn't change state. I see your point about consistency between subcommands. Subcommands *should* be consistent by default. Where I disagree is that, IMO, "read" subcommands behaving differently from "write" subcommands isn't an inconsistency; it's expected. For example, I can see myself trying to use `foo list` to check if the `foo` daemon is running but not to start the daemon.

I actually have a story about `adb`. I remember an issue caused by adb starting the daemon by default. It led to a briefly confusing version conflict. The issue was similar to https://stackoverflow.com/a/26763766. IIRC, I had a generic Android SDK installed and also one from the phone manufacturer. The latter was necessary to flash new firmware to the phone and/or root it. It didn't work because I accidentally had listed devices with generic `adb` and started an incompatible daemon.

That said, I very rarely use `adb`. What `adb` does may be the better default for most of its users most of the time.

> hmm, interesting, I was just using avahi where -D means to daemonize, but obviously tmux is much more relavant here. I can switch it it `-d`

Sorry, I was mistaken about the common meaning of `-D`. `-D` doesn't actually seem to have a set meaning regarding demonization. You mentioned Avahi, and I went digging through my system's man pages. smbd, strace, and PulseAudio also use `-D` to mean "daemonize". On the other hand, lighttpd and sshd use it to mean "do not daemonize". It is a bit of a mess, and `-D` for "daemonize" is actually more prevalent on my system. (The most common meaning of `-D` in the man pages was "debug" and "define a variable".)

In any case, my argument about it `-D` being a convention was wrong. It probably still makes sense to switch to `-d`, but only because of tmux, not some broader convention.

**Comment by qaqland** [comment]
> since we should first try to use systemd and the fallback on autodamonization

As an Alpine Linux user, it would be great to set default behavior(try systemd or not) in config file

**Comment by ethanpailes** [comment]
> In any case, my argument about it -D being a convention was wrong. It probably still makes sense to switch to -d, but only because of tmux, not some broader convention.

Yeah agreed, I think tmux should get a massive disproportinate weighting when it comes to seeing what other tools do.

> As an Alpine Linux user, it would be great to set default behavior(try systemd or not) in config file

Yeah, that makes sense. I think what I'm leaning towards at this point is to have autodaemonization be on by default, with a config option to change the default behavior and a flag to override the config value if desired.

**Comment by merrickluo** [comment]
no opinion on the flag would be happy to have it so I can finally try it out on my systemd-less system :wink:

**Comment by ethanpailes** [comment]
Ok, I've just incorperated this discussion into the patch (https://github.com/shell-pool/shpool/issues/56), thanks everyone for your input, I really appreciate the bikeshedding help. I think it made the first version of this feature better than it would have been.

**Comment by dbohdan** [comment]
I like that shpool has ended up with a `-d`/`--daemonize` and a `-D`/`--no-daemonize` flag and a config option. I have tried aeb949be7dd3f4c149a5105aea06ff8297956e06 on Void Linux, a distro that doesn't use systemd. It works!

If you just run `shpool list` without a `--socket` argument and neither of the directories `$XDG_RUNTIME_DIR/shpool/` and `$HOME/.shpool/shpool/` exists, shpool doesn't successfully launch a daemon. You get this error instead:

    Error: daemonizing: launched daemon, but control socket never came up

You have to create `$XDG_RUNTIME_DIR/shpool/` or `$HOME/.shpool/shpool/` manually. shpool could create its runtime directory in autodaemonization mode. 

(Is the path `$HOME/.shpool/shpool/` nested like this on purpose?)

**Comment by ethanpailes** [comment]
Yeah ~/.shpool doesn't really make sense. I think ~/.local/run might be better and this is already a breaking change so I'll switch it (not that I expect anyone was really relying on this).

I'll also make sure the runtime dir exists right after we resolve it.
