### ISSUE TITLE
Shouldn't shpool detach before attaching?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [shell-pool/shpool#61]
I just noticed that we can attach sessionA then from sessionA attach sessionB and both sessionA and sessionB appear as attached. Is that intended?

**Comment by ethanpailes** [comment]
Yeah, this is intended and in fact required if I understand what you are saying right.

Shpool has no visibility into what is going on inside a session, so if you run `shpool attach othersession` inside one session, there is no way for the outer session handler to notice that and do something special. We could have the inner `shpool attach` process key off `$SHPOOL_SESSION_NAME` and do the detach, but that would still break things because the inner session has no way to attach itself to the pty that invoked the outer attach process.

If you want to switch sessions you need to detach first then attach to the new session.

**Comment by thiswillbeyourgithub** [comment]
Alright thanks!
