### ISSUE TITLE
shpool hangs when the users shell init is interactive

### ISSUE THREAD

**Issue by renatopereyra** [shell-pool/shpool#64]
## What happened

1. `shpool attach main` hangs indefinitely without actually
initializing/attaching a session.
2. `RemoteCommand shpool attach -f "ssh-$(basename $(tty))" --ttl 3d` in my ssh config allows me to get a shpool session but the terminal is not responsive at all.

## What I expected to happen

The above should work.

## Steps to Reproduce

I don't need to do anything other than (1) and (2) above to reproduce this issue. I'm not sure if there is something about my device state affecting this.

**Version info**

shpool 0.6.2 (cl/644227083)

**Logs**
From `shpool -vv -l ~/shpool-daemon.log -s /tmp/shpool.sock daemon`:
[shpool-daemon.log](https://github.com/user-attachments/files/15958341/shpool-daemon.log)

From `shpool -vv -l ~/shpool-attach.log -s /tmp/shpool.sock attach testsession`:
[shpool-attach.log](https://github.com/user-attachments/files/15958342/shpool-attach.log)

I had to stop both with a CTRL+C since I wasn't getting a session from the `attach`.
---

I have tried, with no success:

1. Reinstall shpool. No change.
2. `systemctl --user stop shpool.socket shpool && rm -rf $XDG_RUNTIME_DIR/shpool/ && pkill shpool` followed by a restart of `shpool.socket` and `shpool`. Still same issue.
3. Switch to the unstable release. Same issue.
4. Wait out multiple days for all the existing sessions to age out. No change.

**Comment by ethanpailes** [comment]
Looking at these logs, I think the issue is with some Google specific telemetry code (that is not in the open source version of shpool). Looks like I spoke to soon when I told you to move the issue here. I'll close the GitHub issue and move back to the internal bug tracker.

For now though, you should be able to work around this by following the open source installation instructions since that will get you a version of shpool that is not instrumented.

**Comment by ethanpailes** [comment]
Did some more debugging internally, and it turns out that this has nothing to do with the telemetry code. @renatopereyra  just had a `sudo` command in his `.bashrc`, and since shpool expects that launching your default shell will terminate with an interactive shell that can executes commands in the usual way, it's prompt prefix setup code gets wedged when the user has an interactive .bashrc.

I think we need to do two things here:

1. Make it so that setting `prompt_prefix = ""` fully disables all prompt setup infra. @renatopereyra already had this setting, so he would not have encountered the issue if we did this.
2. Document this requirement somewhere (possibly in a troubleshooting wiki page). I can imagine some people might want to do things like set up their shell init file to prompt them for a project workspace to switch to or something similar.

**Comment by ethanpailes** [comment]
I added a new [troubleshooting](https://github.com/shell-pool/shpool/wiki/Troubleshooting#shpool-attach-hangs-when-trying-to-launch-a-new-shell) wiki page to document this.

**Comment by ethanpailes** [comment]
https://github.com/shell-pool/shpool/pull/67 will link the troubleshooting page into the README
